### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by realkdc** [SebaGGu619/spotifyBot#1]
sh: cmd: command not found
Traceback (most recent call last):
  File "/Users/drippo/Downloads/spotifyBot-main/main.py", line 20, in <module>
    lista = gw.getWindowsWithTitle('Mozilla Firefox')
AttributeError: module 'pygetwindow' has no attribute 'getWindowsWithTitle'

**Comment by realkdc** [comment]
using mac as well not sure if that's why

**Comment by SebaGGu619** [comment]
The pygetwindow module only supports Windows at the moment. It's planned to be a cross-platform module but for now, it's Windows only. I will add a warning to the readme.
